# Generated by Django 4.2.16 on 2024-10-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptchaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("captcha", models.CharField(max_length=4)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
