# Generated by Django 4.2.16 on 2024-10-20 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team_project", "0002_captchamodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaptchaModel",
        ),
        migrations.RemoveField(
            model_name="user",
            name="captcha",
        ),
    ]
